name: OSM Extender
description: Extend OSM with Automated Tasks

inputs:
  action:
    description: Action to perform
    required: true
  api-id:
    description: OSM API ID
    required: true
  api-secret:
    description: OSM API Secret
    required: true

runs:
  using: composite
  steps:
    - name: Setup Action
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Run ${{ inputs.action }}
      shell: bash
      env: 
        PIP_DISABLE_PIP_VERSION_CHECK: '1'
        OSM_API_ID: ${{ inputs.api-id }}
        OSM_API_SECRET: ${{ inputs.api-secret }}
        OSM_BASE_URL: https://www.onlinescoutmanager.co.uk
      run:
        pip install -r requirements.txt
        python main.py


