name: OSM Extender
description: Extend OSM with Automated Tasks
author: 1st Nuthall Scout Group
branding: 
  icon: octagon
  color: purple
inputs:
  action:
    description: Action to perform
    required: true

runs:
  using: composite
  steps:
    - name: Setup Action
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run ${{ inputs.action }}
      shell: bash
      env: 
        PIP_DISABLE_PIP_VERSION_CHECK: '1'
      run:
        pip install -r ${{ github.action_path }}/requirements.txt
        python ${{ github.action_path }}/main.py